title: MendelKinship.jl
description: This analysis option computes kinship and other identity coefficients.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
