name = "MendelKinship"
uuid = "82a28c69-7afd-556c-aa99-b3efd3c23126"
keywords = ["OpenMendel", "kinship"]
license = "MIT"
desc = "Kinship calculations; part of the OpenMendel project."
authors = ["Kenneth Lange <klange@ucla.edu>", "Eric Sobel <esobel@ucla.edu>", "Ben Chu <benchu99@hotmail.com>", "OpenMendel Team"]
version = "0.8.8"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MendelBase = "4fb2d825-8540-5432-a3a3-b9ff66df2cb5"
MendelSearch = "4fa469e6-9890-5c68-874e-584f43f9cdde"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
SnpArrays = "4e780e97-f5bf-4111-9dc4-b70aaf691b06"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
CSV = "0.8"
DataFrames = "0.20, 0.21, 0.22, 1"
PlotlyJS = "0.18"
SnpArrays = "0.3"
StatsBase = "0.33"
WebIO = "0.8"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
